import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { getData } from "./utils/fetchData";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getData("/product/allcategory");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar data={data}/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
